# Generated by Django 5.1 on 2024-11-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('campaign_image', models.ImageField(upload_to='campaign_images/')),
            ],
        ),
    ]
